postgres:
        image: conductdocker/docker-pg
        expose:
                - "5432"
opendj:
        image: conductdocker/docker-dj
        expose:
                - "4444"
                - "8989"
                - "1389"
                - "1636"
proxy:
        image: conductdocker/docker-proxy
        ports:
                - "443:443"
                - "80:80"
                - "636:636"
                - "389:389"
        links: 
                - opendj
openam:
        image: conductdocker/docker-am
        expose:
                - "8443"
                - "8080"
        links:  
                - proxy:dj
openidm:
        image: conductdocker/docker-idm
        expose:
                - "8443"
                - "8444"
                - "8080"
        links:
                - proxy:dj
                - proxy:am
                - postgres:pg
