am:
        image: conductdocker/docker-am
        ports: 
                - "8080:8080"
        links:  
                - dj
dj:
        image: conductdocker/docker-dj
idm:
        image: conductdocker/docker-idm
        ports:
                - "9443:8443"
                - "9080:8080"
        links:
                - am
                - dj
                - pg
pg:
        image: conductdocker/docker-pg
